"""Core CAD, electrical, and manufacturing operations."""

from acd.core.cad_normalize import CadNormalizationError, normalize_3mf, normalize_step
from acd.core.fab import (
    FabOrderIntentView,
    FabProfile,
    FabProfileRegistry,
    ProcessAllowanceView,
    extract_fab_intent,
    load_fab_profile,
    load_fab_profile_by_id,
    load_fab_profile_registry,
    resolve_fab_profile_path,
    validate_allowances_against_profile,
)
from acd.core.feedback import (
    FeedbackError,
    propose_input_feedback,
    validate_applied_feedback,
)
from acd.core.firmware import (
    FunctionalRunError,
    evaluate_functional_run,
    load_and_evaluate_functional_run,
)
from acd.core.firmware_consistency import (
    FirmwareConsistencyReport,
    check_firmware_graph_consistency,
    evaluate_firmware_graph_consistency,
)
from acd.core.functional_blocks import (
    FunctionalBlockContractError,
    FunctionalBlockRegistry,
    declared_functional_blocks,
    load_functional_block_registry,
    required_predicate_names,
    validate_predicate_coverage,
)
from acd.core.order_execution import build_dry_run_order_payload
from acd.core.order_submission import (
    DeclaredProviderUnavailable,
    OrderSubmissionProvider,
    build_order_submission_record,
    resolve_order_provider,
)
from acd.core.order_total import (
    OrderSubtotal,
    OrderTotalError,
    OrderTotalResult,
    QuoteCanonicalHash,
    aggregate_order_total,
    order_total_breakdown_hash,
    order_total_result_from_document,
    order_total_result_to_document,
)
from acd.core.quote import (
    FixtureQuoteProvider,
    QuoteFeeSet,
    QuoteProvider,
    QuoteReadError,
    load_quote,
    quote_provider_from_config,
    read_quote,
)
from acd.core.rationale import (
    RATIONALE_EXEMPT_ATTRS,
    REQUIRED_RATIONALE_ATTRS,
    check_rationale_coverage,
    subject_hash_for,
)
from acd.core.receipt import (
    ReceiptReconciliationError,
    ReconciliationReport,
    build_receipt_evidence,
    reconcile_files,
    reconcile_receipt,
)
from acd.core.side_effect_journal import (
    JournalOrderReconstruction,
    SideEffectJournalError,
    append_post_order,
    append_pre_order,
    read_journal,
    reconstruct_order,
)

__all__ = [
    "RATIONALE_EXEMPT_ATTRS",
    "REQUIRED_RATIONALE_ATTRS",
    "CadNormalizationError",
    "DeclaredProviderUnavailable",
    "FabOrderIntentView",
    "FabProfile",
    "FabProfileRegistry",
    "FeedbackError",
    "FirmwareConsistencyReport",
    "FixtureQuoteProvider",
    "FunctionalBlockContractError",
    "FunctionalBlockRegistry",
    "FunctionalRunError",
    "JournalOrderReconstruction",
    "OrderSubmissionProvider",
    "OrderSubtotal",
    "OrderTotalError",
    "OrderTotalResult",
    "ProcessAllowanceView",
    "QuoteCanonicalHash",
    "QuoteFeeSet",
    "QuoteProvider",
    "QuoteReadError",
    "ReceiptReconciliationError",
    "ReconciliationReport",
    "SideEffectJournalError",
    "aggregate_order_total",
    "append_post_order",
    "append_pre_order",
    "build_dry_run_order_payload",
    "build_order_submission_record",
    "build_receipt_evidence",
    "check_firmware_graph_consistency",
    "check_rationale_coverage",
    "declared_functional_blocks",
    "evaluate_firmware_graph_consistency",
    "evaluate_functional_run",
    "extract_fab_intent",
    "load_and_evaluate_functional_run",
    "load_fab_profile",
    "load_fab_profile_by_id",
    "load_fab_profile_registry",
    "load_functional_block_registry",
    "load_quote",
    "normalize_3mf",
    "normalize_step",
    "order_total_breakdown_hash",
    "order_total_result_from_document",
    "order_total_result_to_document",
    "propose_input_feedback",
    "quote_provider_from_config",
    "read_journal",
    "read_quote",
    "reconcile_files",
    "reconcile_receipt",
    "reconstruct_order",
    "required_predicate_names",
    "resolve_fab_profile_path",
    "resolve_order_provider",
    "subject_hash_for",
    "validate_allowances_against_profile",
    "validate_applied_feedback",
    "validate_predicate_coverage",
]
