"""Shared stdlib helpers for ACD OpenHands hooks."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, cast

REASON = (
    "Derived projections are regenerated by the pipeline; "
    "edit design inputs (graph.json / profiles) instead."
)


def event() -> dict[str, Any]:
    try:
        value: Any = json.load(sys.stdin)
        return cast(dict[str, Any], value) if isinstance(value, dict) else {}
    except (json.JSONDecodeError, OSError):
        return {}


def result(**values: str) -> None:
    print(json.dumps(values, ensure_ascii=True))


def strings(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        mapping = cast(dict[Any, Any], value)
        children: list[Any] = list(mapping.values())
        return [item for child in children for item in strings(child)]
    if isinstance(value, list):
        children = cast(list[Any], value)
        return [item for child in children for item in strings(child)]
    return []


def project_dir(payload: dict[str, Any]) -> Path:
    return Path(
        os.environ.get("OPENHANDS_PROJECT_DIR") or payload.get("working_dir") or "."
    ).resolve()


def revision(root: Path) -> str | None:
    try:
        if subprocess.run(["git", "diff", "--quiet"], cwd=root, check=False).returncode != 0:
            return None
        if (
            subprocess.run(["git", "diff", "--cached", "--quiet"], cwd=root, check=False).returncode
            != 0
        ):
            return None
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=root, text=True).strip()
    except (OSError, subprocess.CalledProcessError):
        return None
