"""Shared stdlib helpers for ACD OpenHands hooks."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, cast

REASON = (
    "Derived projections are regenerated by the pipeline; "
    "edit design inputs (graph.json / profiles) instead. Pipeline output "
    "options and the fail-closed stop report are permitted."
)
STOP_REPORT_PATH = "out/stop-report.json"


def event() -> dict[str, Any]:
    try:
        value: Any = json.load(sys.stdin)
        return cast(dict[str, Any], value) if isinstance(value, dict) else {}
    except (json.JSONDecodeError, OSError):
        return {}


def result(**values: str) -> None:
    print(json.dumps(values, ensure_ascii=True))


def strings(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        mapping = cast(dict[Any, Any], value)
        children: list[Any] = list(mapping.values())
        return [item for child in children for item in strings(child)]
    if isinstance(value, list):
        children = cast(list[Any], value)
        return [item for child in children for item in strings(child)]
    return []


def project_dir(payload: dict[str, Any]) -> Path:
    return Path(
        os.environ.get("OPENHANDS_PROJECT_DIR") or payload.get("working_dir") or "."
    ).resolve()


def revision(root: Path, graph_paths: list[str]) -> str | None:
    try:
        changed = subprocess.check_output(
            ["git", "status", "--porcelain", "--untracked-files=all"],
            cwd=root,
            text=True,
            encoding="utf-8",
        )
        if any(_is_design_input(line[3:]) for line in changed.splitlines() if len(line) > 3):
            return None
        if len(graph_paths) != 1:
            return None
        graph_path = root / graph_paths[0]
        validated = subprocess.run(
            [
                "uv",
                "run",
                "--project",
                str(root),
                "acd-design-revision",
                str(graph_path),
            ],
            cwd=root,
            capture_output=True,
            text=True,
            encoding="utf-8",
            check=False,
        )
        revision = validated.stdout.strip()
        return revision if validated.returncode == 0 and revision else None
    except (OSError, subprocess.CalledProcessError, ValueError, TypeError):
        return None


def _is_design_input(path: str) -> bool:
    return (path.startswith("fixtures/") and path.endswith("/graph.json")) or path.startswith(
        "profiles/"
    )
