"""OpenHands SDK ToolDefinitions for deterministic ACD entrypoints.

The tool families live in sibling modules; this module keeps the public import
surface and the ordered registration manifest.
"""

from __future__ import annotations

from typing import Any

from openhands.sdk.tool import ToolDefinition, list_registered_tools
from openhands.sdk.tool.registry import register_tool  # pyright: ignore[reportUnknownVariableType]

from acd.openhands.tools._base import AcdObservation
from acd.openhands.tools.design_loop_tools import (
    AcdAggregateOrderTotal,
    AcdAggregateOrderTotalAction,
    AcdAggregateOrderTotalExecutor,
    AcdAggregateOrderTotalObservation,
    AcdBuildDesignFixture,
    AcdBuildDesignFixtureAction,
    AcdBuildDesignFixtureExecutor,
    AcdBuildDesignFixtureObservation,
    AcdCheckOrderReadiness,
    AcdCheckOrderReadinessAction,
    AcdCheckOrderReadinessExecutor,
    AcdCheckOrderReadinessObservation,
    AcdCompileRequirementChange,
    AcdCompileRequirementChangeAction,
    AcdCompileRequirementChangeExecutor,
    AcdCompileRequirementChangeObservation,
    AcdDiagnoseGateFailure,
    AcdDiagnoseGateFailureAction,
    AcdDiagnoseGateFailureExecutor,
    AcdDiagnoseGateFailureObservation,
    AcdExploreBoardCandidates,
    AcdExploreBoardCandidatesAction,
    AcdExploreBoardCandidatesExecutor,
    AcdExploreBoardCandidatesObservation,
    AcdExploreEnclosureCandidates,
    AcdExploreEnclosureCandidatesAction,
    AcdExploreEnclosureCandidatesExecutor,
    AcdExploreEnclosureCandidatesObservation,
    AcdRunDesignLoop,
    AcdRunDesignLoopAction,
    AcdRunDesignLoopExecutor,
    AcdRunDesignLoopObservation,
)
from acd.openhands.tools.pipeline_tools import (
    AcdBootstrapWorkspace,
    AcdBootstrapWorkspaceAction,
    AcdBootstrapWorkspaceExecutor,
    AcdBootstrapWorkspaceObservation,
    AcdProbeTools,
    AcdProbeToolsAction,
    AcdProbeToolsExecutor,
    AcdProbeToolsObservation,
    AcdRunBoardPipeline,
    AcdRunBoardPipelineAction,
    AcdRunBoardPipelineExecutor,
    AcdRunBoardPipelineObservation,
    AcdRunEnclosurePipeline,
    AcdRunEnclosurePipelineAction,
    AcdRunEnclosurePipelineExecutor,
    AcdRunEnclosurePipelineObservation,
    AcdRunFirmwarePipeline,
    AcdRunFirmwarePipelineAction,
    AcdRunFirmwarePipelineExecutor,
    AcdRunFirmwarePipelineObservation,
    AcdValidateDesignGraph,
    AcdValidateDesignGraphAction,
    AcdValidateDesignGraphExecutor,
    AcdValidateDesignGraphObservation,
    run_board,
    run_bootstrap,
    run_enclosure,
)
from acd.openhands.tools.registry_tools import (
    AcdRegisterFirmwareCapability,
    AcdRegisterFirmwareCapabilityAction,
    AcdRegisterFirmwareCapabilityExecutor,
    AcdRegisterFirmwareCapabilityObservation,
    AcdRegisterFunctionalBlock,
    AcdRegisterFunctionalBlockAction,
    AcdRegisterFunctionalBlockExecutor,
    AcdRegisterFunctionalBlockObservation,
    AcdRegisterPartsCatalogEntry,
    AcdRegisterPartsCatalogEntryAction,
    AcdRegisterPartsCatalogEntryExecutor,
    AcdRegisterPartsCatalogEntryObservation,
)

__all__ = [
    "ACD_TOOL_DEFINITIONS",
    "AcdAggregateOrderTotal",
    "AcdAggregateOrderTotalAction",
    "AcdAggregateOrderTotalExecutor",
    "AcdAggregateOrderTotalObservation",
    "AcdBootstrapWorkspace",
    "AcdBootstrapWorkspaceAction",
    "AcdBootstrapWorkspaceExecutor",
    "AcdBootstrapWorkspaceObservation",
    "AcdBuildDesignFixture",
    "AcdBuildDesignFixtureAction",
    "AcdBuildDesignFixtureExecutor",
    "AcdBuildDesignFixtureObservation",
    "AcdCheckOrderReadiness",
    "AcdCheckOrderReadinessAction",
    "AcdCheckOrderReadinessExecutor",
    "AcdCheckOrderReadinessObservation",
    "AcdCompileRequirementChange",
    "AcdCompileRequirementChangeAction",
    "AcdCompileRequirementChangeExecutor",
    "AcdCompileRequirementChangeObservation",
    "AcdDiagnoseGateFailure",
    "AcdDiagnoseGateFailureAction",
    "AcdDiagnoseGateFailureExecutor",
    "AcdDiagnoseGateFailureObservation",
    "AcdExploreBoardCandidates",
    "AcdExploreBoardCandidatesAction",
    "AcdExploreBoardCandidatesExecutor",
    "AcdExploreBoardCandidatesObservation",
    "AcdExploreEnclosureCandidates",
    "AcdExploreEnclosureCandidatesAction",
    "AcdExploreEnclosureCandidatesExecutor",
    "AcdExploreEnclosureCandidatesObservation",
    "AcdObservation",
    "AcdProbeTools",
    "AcdProbeToolsAction",
    "AcdProbeToolsExecutor",
    "AcdProbeToolsObservation",
    "AcdRegisterFirmwareCapability",
    "AcdRegisterFirmwareCapabilityAction",
    "AcdRegisterFirmwareCapabilityExecutor",
    "AcdRegisterFirmwareCapabilityObservation",
    "AcdRegisterFunctionalBlock",
    "AcdRegisterFunctionalBlockAction",
    "AcdRegisterFunctionalBlockExecutor",
    "AcdRegisterFunctionalBlockObservation",
    "AcdRegisterPartsCatalogEntry",
    "AcdRegisterPartsCatalogEntryAction",
    "AcdRegisterPartsCatalogEntryExecutor",
    "AcdRegisterPartsCatalogEntryObservation",
    "AcdRunBoardPipeline",
    "AcdRunBoardPipelineAction",
    "AcdRunBoardPipelineExecutor",
    "AcdRunBoardPipelineObservation",
    "AcdRunDesignLoop",
    "AcdRunDesignLoopAction",
    "AcdRunDesignLoopExecutor",
    "AcdRunDesignLoopObservation",
    "AcdRunEnclosurePipeline",
    "AcdRunEnclosurePipelineAction",
    "AcdRunEnclosurePipelineExecutor",
    "AcdRunEnclosurePipelineObservation",
    "AcdRunFirmwarePipeline",
    "AcdRunFirmwarePipelineAction",
    "AcdRunFirmwarePipelineExecutor",
    "AcdRunFirmwarePipelineObservation",
    "AcdValidateDesignGraph",
    "AcdValidateDesignGraphAction",
    "AcdValidateDesignGraphExecutor",
    "AcdValidateDesignGraphObservation",
    "register_acd_tools",
    "run_board",
    "run_bootstrap",
    "run_enclosure",
]


ACD_TOOL_DEFINITIONS: tuple[tuple[str, type[ToolDefinition[Any, Any]]], ...] = (
    ("acd_probe_tools", AcdProbeTools),
    ("acd_validate_design_graph", AcdValidateDesignGraph),
    ("acd_run_board_pipeline", AcdRunBoardPipeline),
    ("acd_run_enclosure_pipeline", AcdRunEnclosurePipeline),
    ("acd_register_functional_block", AcdRegisterFunctionalBlock),
    ("acd_register_firmware_capability", AcdRegisterFirmwareCapability),
    ("acd_register_parts_catalog_entry", AcdRegisterPartsCatalogEntry),
    ("acd_bootstrap_workspace", AcdBootstrapWorkspace),
    ("acd_run_firmware_pipeline", AcdRunFirmwarePipeline),
    ("acd_compile_requirement_change", AcdCompileRequirementChange),
    ("acd_build_design_fixture", AcdBuildDesignFixture),
    ("acd_aggregate_order_total", AcdAggregateOrderTotal),
    ("acd_explore_board_candidates", AcdExploreBoardCandidates),
    ("acd_explore_enclosure_candidates", AcdExploreEnclosureCandidates),
    ("acd_diagnose_gate_failure", AcdDiagnoseGateFailure),
    ("acd_check_order_readiness", AcdCheckOrderReadiness),
    ("acd_run_design_loop", AcdRunDesignLoop),
)


def register_acd_tools() -> None:
    """Register ACD ToolDefinitions without import-time side effects."""
    registered = set(list_registered_tools())
    for name, tool in ACD_TOOL_DEFINITIONS:
        if name not in registered:
            register_tool(name, tool)
            registered.add(name)
