"""Verify the generated OpenHands SDK capability catalog."""

from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationError

REPO_ROOT = Path(__file__).resolve().parent.parent
VENDOR_ROOT = REPO_ROOT / "vendor" / "software-agent-sdk"
CATALOG_PATH = REPO_ROOT / "docs" / "openhands-sdk-capabilities.json"
MARKDOWN_PATH = REPO_ROOT / "docs" / "openhands-sdk-capabilities.md"
ROADMAP_PATH = REPO_ROOT / "docs" / "roadmap.md"
START_MARKER = "<!-- generated by scripts/verify_sdk_capabilities.py; do not edit -->"
END_MARKER = "<!-- end generated -->"
COMMIT_RE = re.compile(r"^[0-9a-f]{40}$")
ADOPTIONS = ("採用", "採用予定", "不採用")
EXCLUDED_MODULE_PATHS = {"workspace": {("docker", "dev_workspace.py")}}
REFERENCE_KINDS = (
    "direct_import",
    "sdk_internal",
    "plugin_asset",
    "test_direct_import",
)
REFERENCE_KIND_LABELS = {
    "direct_import": "直接import",
    "sdk_internal": "SDK内部経路",
    "plugin_asset": "plugin資材",
    "test_direct_import": "テスト直接import",
}
REFERENCE_ROOTS = {
    "direct_import": ("src/acd", "plugins/acd", "scripts"),
    "sdk_internal": ("src/acd", "plugins/acd", "scripts"),
    "plugin_asset": ("plugins/acd",),
    "test_direct_import": ("tests",),
}


class ScannedPackage(BaseModel):
    """A package included in the AST scan."""

    model_config = ConfigDict(extra="forbid")

    prefix: str
    path: str


class NonTargetPackage(BaseModel):
    """A package intentionally outside the capability scan."""

    model_config = ConfigDict(extra="forbid")

    prefix: str
    path: str
    reason: str


class CapabilityReference(BaseModel):
    """A repository reference supporting one capability adoption claim."""

    model_config = ConfigDict(extra="forbid")

    kind: Literal[
        "direct_import",
        "sdk_internal",
        "plugin_asset",
        "test_direct_import",
    ]
    path: str
    symbol: str = Field(min_length=1)
    note: str


def _empty_references() -> list[CapabilityReference]:
    """Return an empty typed reference list for Pydantic defaults."""
    return []


class Capability(BaseModel):
    """One manually reviewed capability claim."""

    model_config = ConfigDict(extra="forbid")

    domain: str
    modules: list[str] = Field(min_length=1)
    representative_apis: list[str] = Field(min_length=1)
    use: str
    adoption: Literal["採用", "採用予定", "不採用"]
    rationale: str
    verification: str
    references: list[CapabilityReference] = Field(default_factory=_empty_references)
    roadmap: str | None = None


class CapabilityCatalog(BaseModel):
    """The single source of truth for SDK capability adoption."""

    model_config = ConfigDict(extra="forbid")

    sdk_version: str
    submodule_commit: str
    scanned_packages: list[ScannedPackage] = Field(min_length=1)
    non_target_packages: list[NonTargetPackage]
    capabilities: list[Capability] = Field(min_length=1)


def _package_modules(prefix: str, package_path: Path) -> dict[str, set[str]]:
    """Extract public top-level symbols from one package tree."""
    modules: dict[str, set[str]] = {}
    if not package_path.is_dir():
        raise ValueError(f"scan package does not exist: {package_path}")
    for source in sorted(package_path.rglob("*.py")):
        relative = source.relative_to(package_path)
        if relative.parts in EXCLUDED_MODULE_PATHS.get(prefix, set()):
            continue
        if any(
            part in {"build", "tests", "__pycache__"} or part.startswith("_")
            for part in relative.parts[:-1]
        ):
            continue
        if relative.name.startswith("_") and relative.name != "__init__.py":
            continue
        parts = list(relative.parts)
        if parts[-1] == "__init__.py":
            parts = parts[:-1]
        else:
            parts[-1] = parts[-1][:-3]
        module = ".".join([prefix, *parts])
        try:
            tree = ast.parse(source.read_text(encoding="utf-8"), filename=str(source))
        except (OSError, SyntaxError) as exc:
            raise ValueError(f"cannot parse SDK module: {source}") from exc
        symbols = {
            node.name
            for node in tree.body
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))
            and not node.name.startswith("_")
        }
        for node in tree.body:
            targets: list[ast.expr] = []
            if isinstance(node, ast.Assign):
                targets = node.targets
                value = node.value
            elif isinstance(node, ast.AnnAssign):
                targets = [node.target]
                value = node.value
            else:
                continue
            if not any(
                isinstance(target, ast.Name) and target.id == "__all__"
                for target in targets
            ):
                continue
            if not isinstance(value, (ast.List, ast.Tuple)):
                continue
            if any(
                not isinstance(element, ast.Constant)
                or not isinstance(element.value, str)
                for element in value.elts
            ):
                raise ValueError(f"__all__ must contain only string literals: {source}")
            for element in value.elts:
                if isinstance(element, ast.Constant) and isinstance(element.value, str):
                    symbols.add(element.value)
        modules[module] = symbols
    return modules


def extract_public_modules(
    scanned_packages: list[ScannedPackage] | None = None,
) -> dict[str, set[str]]:
    """Extract all public modules from the catalog's pinned package trees."""
    if scanned_packages is None:
        scanned_packages = load_catalog().scanned_packages
    if not scanned_packages:
        raise ValueError("scanned_packages is empty")
    modules: dict[str, set[str]] = {}
    for package in scanned_packages:
        path = REPO_ROOT / package.path
        package_modules = _package_modules(package.prefix, path)
        if not package_modules:
            raise ValueError(f"scan package is empty: {package.path}")
        modules.update(package_modules)
    if not modules:
        raise ValueError("no public SDK modules were extracted")
    return modules


def _read_version() -> str:
    """Read the pinned SDK version from its package metadata."""
    pyproject = VENDOR_ROOT / "openhands-sdk" / "pyproject.toml"
    match = re.search(
        r'^version\s*=\s*"([^"]+)"\s*$',
        pyproject.read_text(encoding="utf-8"),
        re.MULTILINE,
    )
    if match is None:
        raise ValueError("SDK version is missing from pyproject.toml")
    return match.group(1)


def _submodule_commit() -> str:
    """Read the exact pinned submodule commit."""
    completed = subprocess.run(
        ["git", "-C", str(VENDOR_ROOT), "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    commit = completed.stdout.strip()
    if completed.returncode != 0 or not COMMIT_RE.fullmatch(commit):
        raise ValueError("software-agent-sdk commit is unavailable or malformed")
    return commit


def load_catalog() -> CapabilityCatalog:
    """Load and validate the catalog JSON."""
    return CapabilityCatalog.model_validate_json(CATALOG_PATH.read_text(encoding="utf-8"))


def _matches(pattern: str, module: str) -> bool:
    """Match an exact module name or a descendant prefix glob."""
    if pattern.endswith(".*"):
        return module.startswith(pattern[:-2] + ".")
    return pattern == module


def _api_name(value: str) -> str:
    """Extract a symbol name from a representative API description."""
    return value.split("(", 1)[0].rsplit(".", 1)[-1].strip()


def _reference_path(reference: CapabilityReference) -> Path:
    """Resolve and validate one repository-relative reference path."""
    relative = Path(reference.path)
    if relative.is_absolute() or ".." in relative.parts:
        raise ValueError(f"reference path must be relative: {reference.path}")
    roots = tuple((REPO_ROOT / root).resolve() for root in REFERENCE_ROOTS[reference.kind])
    path = (REPO_ROOT / relative).resolve()
    if not any(path == root or root in path.parents for root in roots):
        raise ValueError(
            f"{reference.kind} reference path is outside allowed roots: "
            f"{reference.path}"
        )
    if not path.is_file():
        raise ValueError(f"reference path does not exist: {reference.path}")
    if reference.kind == "plugin_asset" and path.suffix not in {".md", ".json"}:
        raise ValueError(f"plugin reference must be Markdown or JSON: {reference.path}")
    return path


def _imported_symbols(path: Path) -> set[str]:
    """Extract symbols imported from public OpenHands modules."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, SyntaxError, UnicodeDecodeError) as exc:
        raise ValueError(f"cannot parse reference source: {path}") from exc
    symbols: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom):
            continue
        if node.module is None or not node.module.startswith("openhands."):
            continue
        symbols.update(alias.name for alias in node.names if alias.name != "*")
    return symbols


def _identifiers(path: Path) -> set[str]:
    """Extract identifiers used by a Python reference source."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, SyntaxError, UnicodeDecodeError) as exc:
        raise ValueError(f"cannot parse reference source: {path}") from exc
    identifiers: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            identifiers.add(node.id)
        elif isinstance(node, ast.Attribute):
            identifiers.add(node.attr)
        elif isinstance(node, ast.keyword) and node.arg is not None:
            identifiers.add(node.arg)
    return identifiers


def _validate_reference(
    capability: Capability,
    reference: CapabilityReference,
) -> str | None:
    """Validate one adoption reference and return an error when invalid."""
    try:
        path = _reference_path(reference)
    except ValueError as exc:
        return f"{capability.domain}: {exc}"
    if reference.kind in {"direct_import", "test_direct_import"}:
        api_names = {_api_name(api) for api in capability.representative_apis}
        if reference.symbol not in api_names:
            return (
                f"{capability.domain}: {reference.kind} symbol is not a "
                f"representative API: {reference.symbol}"
            )
        try:
            imported = _imported_symbols(path)
        except ValueError as exc:
            return f"{capability.domain}: {exc}"
        if reference.symbol not in imported:
            return (
                f"{capability.domain}: {reference.symbol} is not directly "
                f"imported from an openhands module: {reference.path}"
            )
    elif reference.kind == "sdk_internal":
        if not reference.note.strip():
            return f"{capability.domain}: SDK internal reference note is empty"
        try:
            identifiers = _identifiers(path)
        except ValueError as exc:
            return f"{capability.domain}: {exc}"
        if reference.symbol not in identifiers:
            return (
                f"{capability.domain}: SDK internal symbol is absent: "
                f"{reference.symbol} ({reference.path})"
            )
    elif reference.symbol not in path.read_text(encoding="utf-8"):
        return (
            f"{capability.domain}: plugin token is absent: "
            f"{reference.symbol} ({reference.path})"
        )
    return None


def render_markdown(catalog: CapabilityCatalog) -> str:
    """Render the deterministic catalog table block."""
    rows = [
        START_MARKER,
        "",
        f"> 対象: v{catalog.sdk_version} / submodule commit `{catalog.submodule_commit}`",
        ">",
        "> 対象SDKより新しい上流release tagはない。"
        "pinned checkoutをAST traversalして機械抽出した。",
        "> 「採用」はドメインとして採用を決定し、現行コード・plugin資材または"
        "SDK内部経路を通じて使用中、",
        "> 「採用予定」は未使用だが採用を決定済み、「不採用」は採用しないと決定した能力を表す。",
        "> 代表APIの直接importがない場合も、ACDから渡す設定・SDKの実行経路・"
        "plugin資材の参照を根拠に含める。",
        "",
        "| 能力ドメイン（パッケージ） | 代表API | ACDでの用途 | 採否 | 根拠 | 検証手段 |",
        "|---|---|---|---|---|---|",
    ]
    for capability in catalog.capabilities:
        apis = "<br>".join(f"`{api}`" for api in capability.representative_apis)
        adoption = capability.adoption
        if capability.adoption == "採用予定":
            adoption = f"採用予定（ロードマップ{capability.roadmap}）"
        rows.append(
            "| "
            + " | ".join(
                (
                    capability.domain,
                    apis,
                    capability.use,
                    adoption,
                    capability.rationale,
                    capability.verification,
                )
            )
            + " |"
        )
    adopted = [capability for capability in catalog.capabilities if capability.adoption == "採用"]
    if adopted:
        rows.extend(("", "## 採用行の参照先", ""))
        for capability in adopted:
            for reference in capability.references:
                kind = REFERENCE_KIND_LABELS[reference.kind]
                rows.append(
                    f"- `{capability.domain}`: **{kind}** `{reference.path}` / "
                    f"`{reference.symbol}` — {reference.note}"
                )
    for package in catalog.non_target_packages:
        rows.extend(("", f"{package.prefix}は{package.reason}。"))
    rows.extend(("", END_MARKER))
    return "\n".join(rows)


def _markdown_block() -> str:
    """Read the generated block from the documentation."""
    text = MARKDOWN_PATH.read_text(encoding="utf-8")
    start = text.find(START_MARKER)
    end = text.find(END_MARKER)
    if start < 0 or end < 0 or end < start:
        raise ValueError("generated Markdown block markers are missing or reversed")
    return text[start : end + len(END_MARKER)]


def validate_catalog(catalog: CapabilityCatalog, modules: dict[str, set[str]]) -> list[str]:
    """Return every deterministic catalog validation error."""
    errors: list[str] = []
    try:
        commit = _submodule_commit()
    except (OSError, ValueError):
        commit = ""
    if catalog.submodule_commit != commit:
        errors.append("submodule_commit does not match vendor/software-agent-sdk HEAD")
    try:
        version = _read_version()
    except (OSError, ValueError):
        version = ""
    if catalog.sdk_version != version:
        errors.append("sdk_version does not match openhands-sdk/pyproject.toml")

    claims: dict[str, list[str]] = {module: [] for module in modules}
    try:
        roadmap_text = ROADMAP_PATH.read_text(encoding="utf-8")
    except OSError:
        roadmap_text = ""
    for capability in catalog.capabilities:
        if capability.adoption == "採用" and not capability.references:
            errors.append(f"{capability.domain}: 採用には参照宣言が必要")
        elif capability.adoption != "採用" and capability.references:
            errors.append(
                f"{capability.domain}: {capability.adoption}には参照宣言を設定できない"
            )
        for reference in capability.references:
            reference_error = _validate_reference(capability, reference)
            if reference_error is not None:
                errors.append(reference_error)
        for pattern in capability.modules:
            matched = [module for module in modules if _matches(pattern, module)]
            if not matched:
                errors.append(f"{capability.domain}: stale module pattern {pattern}")
            for module in matched:
                claims[module].append(capability.domain)
        if capability.adoption == "採用予定":
            if not capability.roadmap:
                errors.append(f"{capability.domain}: 採用予定 requires roadmap")
            elif capability.roadmap not in roadmap_text:
                errors.append(f"{capability.domain}: roadmap reference is absent")
        elif capability.roadmap is not None:
            errors.append(f"{capability.domain}: roadmap must be null for {capability.adoption}")
        claimed_modules = [
            module
            for module in modules
            if any(_matches(pattern, module) for pattern in capability.modules)
        ]
        for api in capability.representative_apis:
            symbol = _api_name(api)
            if not any(symbol in modules[module] for module in claimed_modules):
                errors.append(f"{capability.domain}: representative API is absent: {api}")

    for module, domains in claims.items():
        if len(domains) == 0:
            errors.append(f"unclaimed module: {module}")
        elif len(domains) > 1:
            errors.append(f"multiply claimed module: {module}: {', '.join(sorted(domains))}")
    domains = [capability.domain for capability in catalog.capabilities]
    if len(domains) != len(set(domains)):
        errors.append("capability domains must be unique")
    if domains != sorted(domains):
        errors.append("capabilities must be sorted by domain")

    for package in catalog.non_target_packages:
        path = REPO_ROOT / package.path
        if not path.is_dir():
            errors.append(f"{package.prefix}: non-target path does not exist: {package.path}")
    try:
        expected = render_markdown(catalog)
        actual = _markdown_block()
        if actual != expected:
            errors.append("generated Markdown block differs from JSON")
    except (OSError, ValueError) as exc:
        errors.append(f"generated Markdown cannot be checked: {exc}")
    return errors


def _parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="check JSON and Markdown drift")
    group.add_argument("--write", action="store_true", help="write the generated Markdown block")
    return parser


def main(argv: list[str] | None = None) -> int:
    """Run the fail-closed capability catalog verification."""
    args = _parser().parse_args(argv)
    try:
        catalog = load_catalog()
        modules = extract_public_modules(catalog.scanned_packages)
        if not modules:
            raise ValueError("no public SDK modules were extracted")
        errors = validate_catalog(catalog, modules)
    except (OSError, ValidationError, ValueError, json.JSONDecodeError) as exc:
        print(f"fail-closed: {exc}", file=sys.stderr)
        return 1
    if args.write:
        text = MARKDOWN_PATH.read_text(encoding="utf-8")
        start = text.find(START_MARKER)
        end = text.find(END_MARKER)
        if start < 0 or end < start:
            print("fail-closed: generated Markdown block markers are missing", file=sys.stderr)
            return 1
        replacement = render_markdown(catalog)
        MARKDOWN_PATH.write_text(
            text[:start] + replacement + text[end + len(END_MARKER) :],
            encoding="utf-8",
        )
        non_drift_errors = [
            error
            for error in errors
            if error != "generated Markdown block differs from JSON"
        ]
        for error in non_drift_errors:
            print(f"error: {error}", file=sys.stderr)
        if non_drift_errors:
            return 1
        return 0
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
